name: Hillel Maven Demo Pipeline

# when to start the pipeline
on: [push]

# defining tasks
jobs:
  compile:
    # defining a container image which will be used for teh pipeline
    runs-on: ubuntu-latest
    # what to do
    steps:
      # copy code from the repo into pipeline container
      - uses: actions/checkout@v3
      # set up java environment
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: nexus-private
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Compile sources
        # run needed commands
        run: mvn --batch-mode clean compile
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}



  test:
    # job it waits to finish for
    needs: compile
    # defining a container image which will be used for teh pipeline
    runs-on: ubuntu-latest
    # what to do
    steps:
      # copy code from the repo into pipeline container
      - uses: actions/checkout@v3
      # set up java environment
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: nexus-private
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Compile sources
        # run needed commands
        run: mvn --batch-mode clean test
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

  package:
    # job it waits to finish for
    needs: compile
    # defining a container image which will be used for teh pipeline
    runs-on: ubuntu-latest
    # what to do
    steps:
      # copy code from the repo into pipeline container
      - uses: actions/checkout@v3
      # set up java environment
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: nexus-private
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Compile sources
        # run needed commands
        run: mvn --batch-mode clean package
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

  publish:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: nexus-private
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
           MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
           MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}